export const portfolioData = {
  personal: {
    name: "Hunain Arshad",
    tagline: "E-Commerce Specialist & Digital Marketing Expert",
    intro:
      "Results-driven E-Commerce Specialist with 2+ years of experience managing Shopify and eBay platforms, optimizing product listings with SEO best practices, and executing data-driven email marketing campaigns. Proven track record in cross-functional collaboration, team leadership, and performance optimization.",
    profileImage: null, // Using direct import in component
    email: "hunainarshad1972@gmail.com",
    location: "Dubai, United Arab Emirates",
  },
  education: [
    {
      id: 1,
      degree: "Bachelor of Science in Computer Science",
      institution: "Government College University (GCU)",
      location: "Lahore, Pakistan",
      period: "2017 - 2021",
      description:
        "Focused on computer science fundamentals, programming concepts, algorithms, and software engineering principles. Strong foundation in technical problem-solving and analytical thinking.",
      icon: "graduation-cap",
    },
    {
      id: 2,
      degree: "Shopify E-Commerce Mastery",
      institution: "Shopify Partner Academy",
      location: "Online",
      period: "2023",
      description:
        "Comprehensive training in Shopify store management, customization, product merchandising, theme development, and advanced e-commerce strategies.",
      icon: "graduation-cap",
    },
    {
      id: 3,
      degree: "Digital Marketing & Email Marketing Certification",
      institution: "HubSpot Academy",
      location: "Online",
      period: "2023",
      description:
        "Mastered email marketing strategies, customer segmentation, automation workflows, A/B testing, and conversion optimization techniques using Mailchimp and Klaviyo.",
      icon: "graduation-cap",
    },
    {
      id: 4,
      degree: "eBay Seller Certification",
      institution: "eBay Seller University",
      location: "Online",
      period: "2024",
      description:
        "Expert-level training in eBay store management, product listing optimization, SEO best practices, inventory management, and multi-channel e-commerce operations.",
      icon: "graduation-cap",
    },
    {
      id: 5,
      degree: "Google Analytics & Performance Tracking",
      institution: "Google Analytics Academy",
      location: "Online",
      period: "2024",
      description:
        "Advanced analytics training including conversion tracking, customer behavior analysis, performance optimization, and data-driven decision making for e-commerce.",
      icon: "graduation-cap",
    },
  ],
  certifications: [
    {
      id: 1,
      name: "Shopify Partner Certification",
      issuer: "Shopify",
      date: "2024",
      credentialId: "SHOP-PARTNER-2024",
      link: "#",
    },
    {
      id: 2,
      name: "Google Analytics Certified",
      issuer: "Google",
      date: "2024",
      credentialId: "GA-CERT-2024",
      link: "#",
    },
    {
      id: 3,
      name: "Email Marketing Specialist",
      issuer: "HubSpot Academy",
      date: "2023",
      credentialId: "HUBSPOT-EMAIL-2023",
      link: "#",
    },
    {
      id: 4,
      name: "eBay Certified Store Manager",
      issuer: "eBay Seller University",
      date: "2024",
      credentialId: "EBAY-CERT-2024",
      link: "#",
    },
    {
      id: 5,
      name: "Digital Marketing Professional",
      issuer: "Google Digital Garage",
      date: "2023",
      credentialId: "GOOGLE-DM-2023",
      link: "#",
    },
  ],
  experience: [
    {
      id: 1,
      company: "The CP Tech Electronic Cigarettes & Accessories L.L.C",
      role: "Senior E-Commerce Specialist",
      location: "Dubai, UAE",
      period: "Jan 2025 - Present",
      description: [
        "Manage end-to-end Shopify e-commerce operations including store customization, product merchandising, and promotional execution resulting in improved conversion rates",
        "Design and execute targeted email marketing campaigns using Shopify, Mailchimp, and Klaviyo, driving measurable improvements in customer engagement and retention",
        "Coordinate cross-functional teams across UAE, UK, and Pakistan to ensure timely product launches and alignment of marketing initiatives with business objectives",
        "Optimize performance tracking systems and implement data-driven strategies to enhance customer experience and operational efficiency",
      ],
      technologies: [
        "Shopify",
        "Mailchimp",
        "Klaviyo",
        "Google Analytics",
        "SEO Optimization",
      ],
    },
    {
      id: 2,
      company: "The CP Tech Electronic Cigarettes & Accessories L.L.C",
      role: "Product Listing Team Lead & Email Marketing",
      location: "Dubai, UAE",
      period: "Jul 2024 - Jan 2025",
      description: [
        "Led product listing team managing Shopify and eBay platforms with focus on SEO optimization, accurate pricing, and inventory variations",
        "Trained and mentored team members on best practices, improving operational efficiency and listing quality standards",
        "Implemented email marketing strategies that boosted customer engagement metrics and conversion performance",
      ],
      technologies: [
        "Shopify",
        "eBay",
        "SEO",
        "Email Marketing",
        "Team Leadership",
      ],
    },
    {
      id: 3,
      company: "The CP Tech Electronic Cigarettes & Accessories L.L.C",
      role: "Product Listing & Order Fulfillment Specialist",
      location: "Dubai, UAE",
      period: "Jan 2024 - Jun 2024",
      description: [
        "Managed product listings across multiple platforms ensuring SEO optimization and data accuracy for enhanced discoverability",
        "Coordinated order processing, dispatch, shipping, and returns to maintain high customer satisfaction and timely delivery",
      ],
      technologies: [
        "Shopify",
        "eBay",
        "Order Management",
        "Inventory Systems",
      ],
    },
    {
      id: 4,
      company: "Hamdard Curriculum Research & Educational Centre",
      role: "Content Writer",
      location: "Lahore, Pakistan",
      period: "Jan 2022 - Aug 2023",
      description: [
        "Developed and edited academic content including Computer Science study guides and examination papers for university students",
        "Ensured content accuracy, clarity, and alignment with educational standards through collaboration with subject specialists",
        "Improved learner comprehension by restructuring instructional materials and implementing quality assurance processes",
      ],
      technologies: [
        "Content Writing",
        "Educational Content",
        "Quality Assurance",
      ],
    },
    {
      id: 5,
      company: "Stars College",
      role: "Computer Science Teacher",
      location: "Lahore, Pakistan",
      period: "Jun 2021 - Aug 2023",
      description: [
        "Delivered structured instruction in Computer Science covering programming fundamentals and practical applications",
        "Designed curriculum-aligned lesson plans, assessments, and learning materials to support student achievement",
        "Enhanced student understanding through clear explanations, hands-on exercises, and continuous performance evaluation",
      ],
      technologies: [
        "Teaching",
        "Curriculum Development",
        "Programming Fundamentals",
      ],
    },
  ],
  projects: [
    {
      id: 1,
      name: "Shopify Store Optimization & Conversion Enhancement",
      description:
        "Led complete overhaul of Shopify e-commerce store, implementing advanced product merchandising strategies, custom theme customization, and conversion optimization techniques. Resulted in 35% increase in conversion rates and 50% improvement in average order value through data-driven A/B testing and performance tracking.",
      techStack: [
        "Shopify",
        "Liquid",
        "Google Analytics",
        "A/B Testing",
        "Conversion Optimization",
      ],
      githubLink: "#",
      liveLink: "#",
      image: null,
    },
    {
      id: 2,
      name: "Automated Email Marketing Campaign System",
      description:
        "Designed and implemented comprehensive email marketing automation workflows using Klaviyo and Mailchimp. Created segmented customer journeys, automated abandoned cart recovery, post-purchase follow-ups, and personalized product recommendations. Achieved 40% increase in email open rates and 25% boost in customer retention.",
      techStack: [
        "Klaviyo",
        "Mailchimp",
        "Email Automation",
        "Customer Segmentation",
        "Analytics",
      ],
      githubLink: "#",
      liveLink: "#",
      image: null,
    },
    {
      id: 3,
      name: "Multi-Platform E-Commerce Management System",
      description:
        "Developed streamlined workflow for managing product listings across Shopify and eBay platforms simultaneously. Implemented SEO optimization strategies, automated inventory synchronization, and standardized pricing models. Reduced listing time by 60% and improved cross-platform consistency.",
      techStack: [
        "Shopify",
        "eBay API",
        "SEO Optimization",
        "Inventory Management",
        "Data Integration",
      ],
      githubLink: "#",
      liveLink: "#",
      image: null,
    },
    {
      id: 4,
      name: "Performance Analytics Dashboard",
      description:
        "Built comprehensive analytics dashboard integrating Google Analytics, Shopify analytics, and email marketing metrics. Created custom reports and KPI tracking systems for real-time performance monitoring. Enabled data-driven decision making and identified key optimization opportunities.",
      techStack: [
        "Google Analytics",
        "Data Visualization",
        "Performance Tracking",
        "KPI Dashboards",
        "Reporting Tools",
      ],
      githubLink: "#",
      liveLink: "#",
      image: null,
    },
    {
      id: 5,
      name: "Team Training & Process Documentation Platform",
      description:
        "Created comprehensive training materials and process documentation for product listing team. Developed best practices guides, SEO optimization checklists, and quality assurance workflows. Improved team efficiency by 45% and standardized listing quality across all platforms.",
      techStack: [
        "Documentation",
        "Process Optimization",
        "Team Training",
        "Quality Assurance",
        "Knowledge Management",
      ],
      githubLink: "#",
      liveLink: "#",
      image: null,
    },
    {
      id: 6,
      name: "Customer Retention & Engagement Program",
      description:
        "Designed and executed multi-channel customer retention strategy combining email marketing, personalized offers, and loyalty programs. Implemented customer segmentation based on purchase behavior and engagement metrics. Increased customer lifetime value by 30% and reduced churn rate by 20%.",
      techStack: [
        "Customer Retention",
        "Email Marketing",
        "Customer Segmentation",
        "Loyalty Programs",
        "Behavioral Analytics",
      ],
      githubLink: "#",
      liveLink: "#",
      image: null,
    },
  ],
  socialLinks: {
    github: "https://github.com/hunainarshad",
    linkedin: "https://linkedin.com/in/hunain-arshad-379a613a0",
    twitter: "#",
    email: "mailto:hunainarshad1972@gmail.com",
  },
};
